# User Test
#------------------------------------
APP              = memradtest
# App sources
APP_SRCS         = memradtest.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       = -DMEM_LEVEL=2
# Linker flags
APP_LDFLAGS      =

# Custom linker
APP_LINK_SCRIPT  =

include $(RULES_DIR)/pmsis_rules.mk
